// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbw7zUAFuIhcPihjj3tGTvsCTYYC-DXLc',
    appId: '1:642681024764:web:b91b4193dfade7848ee779',
    messagingSenderId: '642681024764',
    projectId: 'jeebjab-dev',
    authDomain: 'jeebjab-dev.firebaseapp.com',
    storageBucket: 'jeebjab-dev.firebasestorage.app',
    measurementId: 'G-9Q7KCLV5GC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMNUjcbssftN0DS0SY2yx4C60xIVxSsNc',
    appId: '1:642681024764:android:0fc91269f87c2a478ee779',
    messagingSenderId: '642681024764',
    projectId: 'jeebjab-dev',
    storageBucket: 'jeebjab-dev.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3_aabDBtZJ0AZYStp27dr3tKfQFEJ7gU',
    appId: '1:642681024764:ios:9e940630de12bf1a8ee779',
    messagingSenderId: '642681024764',
    projectId: 'jeebjab-dev',
    storageBucket: 'jeebjab-dev.firebasestorage.app',
    iosClientId: '642681024764-fh4834269s301ft7fkj7bkv8toitjdjc.apps.googleusercontent.com',
    iosBundleId: 'com.titanumtech.jeebjab',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3_aabDBtZJ0AZYStp27dr3tKfQFEJ7gU',
    appId: '1:642681024764:ios:b97032878d5367168ee779',
    messagingSenderId: '642681024764',
    projectId: 'jeebjab-dev',
    storageBucket: 'jeebjab-dev.firebasestorage.app',
    iosClientId: '642681024764-qn5oqb4plj1o12a4ur0dcthj1kns1srv.apps.googleusercontent.com',
    iosBundleId: 'com.lwm.jeebjab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbw7zUAFuIhcPihjj3tGTvsCTYYC-DXLc',
    appId: '1:642681024764:web:46b2a8b44e66bdb18ee779',
    messagingSenderId: '642681024764',
    projectId: 'jeebjab-dev',
    authDomain: 'jeebjab-dev.firebaseapp.com',
    storageBucket: 'jeebjab-dev.firebasestorage.app',
    measurementId: 'G-ZRX0GRQ30H',
  );
}
