// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWoGgDFZJXOqdSA8mz2WCyWj4EJw2bWTc',
    appId: '1:27682003976:web:ade6622e5438d943e6c5bd',
    messagingSenderId: '27682003976',
    projectId: 'jeebjab-preprod',
    authDomain: 'jeebjab-preprod.firebaseapp.com',
    storageBucket: 'jeebjab-preprod.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDefMD0XjWLkidJIucRFDkQf4YlrTccv60',
    appId: '1:27682003976:android:b89ab70e050ba7b7e6c5bd',
    messagingSenderId: '27682003976',
    projectId: 'jeebjab-preprod',
    storageBucket: 'jeebjab-preprod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA84mZmjy9t9KR5y05gVUI09O3JmYAj_XU',
    appId: '1:27682003976:ios:ee9ececba86a63cbe6c5bd',
    messagingSenderId: '27682003976',
    projectId: 'jeebjab-preprod',
    storageBucket: 'jeebjab-preprod.firebasestorage.app',
    iosBundleId: 'com.titanumtech.jeebjab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA84mZmjy9t9KR5y05gVUI09O3JmYAj_XU',
    appId: '1:27682003976:ios:2e6d60d78eb59e8ae6c5bd',
    messagingSenderId: '27682003976',
    projectId: 'jeebjab-preprod',
    storageBucket: 'jeebjab-preprod.firebasestorage.app',
    iosBundleId: 'com.lwm.jeebjab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWoGgDFZJXOqdSA8mz2WCyWj4EJw2bWTc',
    appId: '1:27682003976:web:807c4fae938a0c82e6c5bd',
    messagingSenderId: '27682003976',
    projectId: 'jeebjab-preprod',
    authDomain: 'jeebjab-preprod.firebaseapp.com',
    storageBucket: 'jeebjab-preprod.firebasestorage.app',
  );

}